name: mem_watcher

on:
  push:
    branches:
      - "*"
    paths: 
      - 'eBPF_Supermarket/Memory_Subsystem/mem_watcher/**'
      - '.github/workflows/ebpf_mem_watcher.yml'
  pull_request:
    branches:
      - "*"
    paths:
      - 'eBPF_Supermarket/Memory_Subsystem/mem_watcher/**'
      - '.github/workflows/ebpf_mem_watcher.yml'

jobs:
  mem_watcher-project-build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libbpf-dev clang llvm libelf-dev libpcap-dev gcc-multilib build-essential linux-tools-$(uname -r)
          git submodule update --init --recursive

      - name: Run mem_watcher
        continue-on-error: true
        run: |
          cd eBPF_Supermarket/Memory_Subsystem/vmlinux/x86
          bpftool btf dump file /sys/kernel/btf/vmlinux format c > vmlinux.h
          cd ../../mem_watcher
          make
          sudo ./mem_watcher -N
          sudo timeout 20 ./mem_watcher
